# Generated by Django 3.2.9 on 2021-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211105_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default='https://www.clipartbay.com/cliparts/closed-book-clipart-w9n4l5o.png'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
