# Generated by Django 3.2.9 on 2021-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211105_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='service',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='bookstore_account',
            field=models.IntegerField(default=666666),
        ),
    ]
