# Generated by Django 3.2.9 on 2021-11-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211105_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='isbn',
            new_name='book',
        ),
    ]
