# Generated by Django 3.2.9 on 2021-11-05 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_isbn_transactiondetail_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninfo',
            name='trans_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
