# Generated by Django 3.2.9 on 2021-11-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_transactioninfo_trans_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
