# Generated by Django 3.2.9 on 2021-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_transactiondetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buy_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rent_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
