# Generated by Django 3.2.9 on 2021-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211106_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='service',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
