# Generated by Django 3.2.9 on 2021-11-06 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_cartitem_total_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditCard',
            new_name='Card',
        ),
    ]
